
SERVER_TEMPLATES = {
    "DLTE_EU": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@dog.chocolatemango.live:5444?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=chrome&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "DLTE_RU": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@dog.chocolatemango.live:443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=chrome&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc&sid=6ba85179e30d4fc2",
    "RLTE_EU": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@89.208.87.121:5444?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "RLTE_RU": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@89.208.87.121:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "FLTE_EU": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@fox.chocolatemango.live:5444?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=chrome&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc&sid=6ba85179e30d4fc2",
    "FLTE_RU": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@fox.chocolatemango.live:443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=chrome&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "WLTE_EU": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@rat.chocolatemango.live:5444?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc&sid=6ba85179e30d4fc2",
    "WLTE_RU": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@rat.chocolatemango.live:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "BLTE_EU": "",
    "BLTE_RU": "",
    "SPB_Private": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@rat.chocolatemango.live:55553?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&sni=max.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "SIGN": "vless://perez@127.0.0.1:443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=qq&sni=www.vk.com&pbk=just-a-sign",
    "Finland": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@fi.learnyouthinspire.co.uk:443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=tls&sni=fi.learnyouthinspire.co.uk&fp=chrome&allowInsecure=0",
    "Poland": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@83.166.248.83:2087?encryption=none&flow=xtls-rprx-vision&type=tcp&security=tls&sni=pl.learnyouthinspire.co.uk",
    "France": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@83.166.248.83:443?encryption=none&flow=xtls-rprx-vision&type=tcp&host=fr.learnyouthinspire.co.uk&path=/vless&security=tls&sni=fr.learnyouthinspire.co.uk",
    "Germany": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@de-nuremberg.chocolatemango.live:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=tls&sni=de-nuremberg.chocolatemango.live",
    "Italy": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@83.166.248.83:8443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=tls&sni=it.learnyouthinspire.co.uk",
    "NL_1": "vless://34ac19a1-e8da-41be-832d-a735498c0a51@m.lysenar.ru:32668?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&fp=chrome&sni=www.vk.com&pbk=D63Fub52x76l1DSzYc2XGYzSvaL0N4L3Hj7FN2bAwzg&sid=4993de9c01aa781a&spx=/tCHhkRjvYnFvUqo",
    "Moscow_1": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@89.221.203.3:2443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=chrome&sni=ie.ozone.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "Moscow_2": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@84.252.100.168:2443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=qq&sni=ie.ozone.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "SPB": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@188.225.77.238:2443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=qq&sni=ie.ozone.ru&pbk=SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc",
    "USA": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@usa-il.chocolatemango.live:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=tls&sni=usa-il.chocolatemango.live",
    "NL_2": "vless://9d365a6d-4b01-4932-a0c1-86a2e873a4c1@nl27.linkey35.ru:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&fp=qq&sni=www.vk.com&pbk=TTqkOFxY5de8wuJ8qu9ibe0cA-cbEiP--Pr0iKkHfmg",
    "Finland_Plus": "",
    "Austria": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@at.chocolatemango.live:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=tls&sni=at.chocolatemango.live",
    "LTE_Plus": "vless://9d365a6d-4b01-4932-a0c1-86a2e873a4c1@ruswl1.linkey45.ru:443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=reality&fp=qq&sni=www.x5.ru&pbk=_V2raeSWlCzTlrkTVL5hYNjOxihyv4nO5CedWHDlRyo",
    "Sweden": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@se.learnyouthinspire.co.uk:443?flow=xtls-rprx-vision&type=tcp&headerType=none&security=tls&sni=se.learnyouthinspire.co.uk&fp=chrome&allowInsecure=0",
    "SPB_Private_WiFi": "vless://7bee7ce0-f4c1-4d12-bdc0-a1c8c8e6f30f@led-ru.learnyouthinspire.co.uk:443?flow=&type=ws&host=led-ru.learnyouthinspire.co.uk&path=/vless&security=tls&sni=led-ru.learnyouthinspire.co.uk&fp=chrome&allowInsecure=0",
    "Germany_K": "vless://4bfc0dff-5160-476f-b3a4-e5bea984e83e@node-germany2.squickme.ru:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&fp=chrome&sni=yandex.net&pbk=6IedBM7xY_DRfmWSiRdmoEpQBw8wIsFPUt1a9rGxOlQ&sid=45665445&spx=/",
    "Estonia_S": "vless://aa2c60ea-74cb-468b-b531-fd70516f1449@es.subv.ru:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&fp=qq&sni=es.subv.ru&pbk=ca5sfJNcjkh3oNt51hRexXbGWgITAqCprGSU-YKCJBA&sid=6a59ae0dc685b1c2&spx=/",
    "Poland_S": "vless://aa2c60ea-74cb-468b-b531-fd70516f1449@pl.cdns.su:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&fp=qq&sni=pl.cdns.su&pbk=hSTtlpXKAYVVu5ybX3hQfq8dfsUrO_HoFVgfGGoCHVw&sid=3429a41453f39be2&spx=/",
    "Germany_S": "vless://aa2c60ea-74cb-468b-b531-fd70516f1449@bde.titun.su:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&fp=qq&sni=toz.su&pbk=1vSZjvhZO01oAEH3b7eebR1qF5dLU1Dq2E7xu8pwGSs&sid=428ef87fd47a3a32",
    "Finland_S": "vless://aa2c60ea-74cb-468b-b531-fd70516f1449@fi.jojack.ru:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&fp=qq&sni=fi.jojack.ru&pbk=u26A516I3BCfUMPOo6rw0-XYt0C2sCWaPNP2pNdtxzw&sid=5057ad011c93051b&spx=/",
    "Ukraine_S": "vless://aa2c60ea-74cb-468b-b531-fd70516f1449@fua.subv.ru:443?encryption=none&flow=xtls-rprx-vision&type=tcp&security=reality&fp=qq&sni=fua.subv.ru&pbk=ca5sfJNcjkh3oNt51hRexXbGWgITAqCprGSU-YKCJBA&sid=8dc4fccb2bcfc99d&spx=/",
}

# Настройки подписок: (ID сервера, Кастомное имя)
SUBSCRIPTIONS = {
    "beeline.txt": [
        ("SIGN", "‼️⬇️Только моб. интернет"),
        ("RLTE_EU", "🇪🇺🔵Билайн №1"),
        ("RLTE_RU", "🇷🇺🔵Билайн №2"),
        ("FLTE_EU", "🇪🇺🟠Билайн №3"),
        ("FLTE_RU", "🇷🇺🟠Билайн №4"),
        ("WLTE_EU", "🇪🇺⚪Билайн №5"),
        ("WLTE_RU", "🇷🇺⚪Билайн №6"),
        ("DLTE_EU", "🇪🇺🟢Билайн №7"),
        ("DLTE_RU", "🇷🇺🟢Билайн №8"),
        ("SIGN", "‼️⬇️VPN для Wi-Fi"),
        ("Germany", "🇩🇪🛜Germany"),
        ("Austria", "🇦🇹🛜Austria"),
        ("Poland", "🇵🇱🛜Poland"),
    ],
    "user_polina.txt": [
        ("RLTE_EU", "🇪🇺💙МегаФон №1"),
        ("RLTE_RU", "🇷🇺💙МегаФон №2"),
        ("FLTE_EU", "🇪🇺🧡МегаФон №3"),
        ("FLTE_RU", "🇷🇺🧡МегаФон №4"),
        ("WLTE_EU", "🇪🇺🤍МегаФон №5"),
        ("WLTE_RU", "🇷🇺🤍МегаФон №6"),
        ("DLTE_EU", "🇪🇺💚МегаФон №7"),
        ("DLTE_RU", "🇷🇺💚МегаФон №8"),
        ("SPB_Private", "🇷🇺❤️Дневник (моб.интернет)"),
        ("SIGN", "Если не работает – обнови🔄"),
        #("SIGN", "Never forget 🔄"),
        ("Germany", "🇩🇪🛜Germany №1"),
        ("Poland_S", "🇵🇱🛜Poland №1"),
        ("Poland", "🇵🇱🛜Poland №2"),
        ("NL_2", "🇳🇱🛜Netherlands"),
        ("Estonia_S", "🇪🇪🛜Estonia"),
        ("France", "🇫🇷🛜France"),
        ("Germany_S", "🇩🇪🛜Germany №2"),
        ("Italy", "🇮🇹🛜Italy"),
        ("Ukraine_S", "🇺🇦🛜Ukraine"),
        ("Finland_S", "🇫🇮🛜Finland"),
        ("USA", "🇺🇸🛜USA"),
    ],
    "kustvpn.txt": [
        ("RLTE_EU", "🇪🇺[🍀] 🔵Моб. интернет"),
        ("RLTE_RU", "🇷🇺[🍀] 🔵Моб. интернет"),
        ("FLTE_EU", "🇪🇺[🍀] 🟠Моб. интернет"),
        ("FLTE_RU", "🇷🇺[🍀] 🟠Моб. интернет"),
        ("WLTE_EU", "🇪🇺[🍀] ⚪Моб. интернет"),
        ("WLTE_RU", "🇷🇺[🍀] ⚪Моб. интернет"),
        ("DLTE_EU", "🇪🇺[🍀] 🟢Моб. интернет"),
        ("DLTE_RU", "🇷🇺[🍀] 🟢Моб. интернет"),
        ("SPB_Private", "🇷🇺[🍀] 🔴Дневник (моб.интернет)"),
        ("Germany", "🇩🇪[🍀] 🛜Germany №1"),
        ("Poland_S", "🇵🇱[🍀] 🛜Poland №1"),
        ("Poland", "🇵🇱[🍀] 🛜Poland №2"),
        ("NL_2", "🇳🇱[🍀] 🛜Netherlands"),
        ("Estonia_S", "🇪🇪[🍀] 🛜Estonia"),
        ("France", "🇫🇷[🍀] 🛜France"),
        ("Germany_S", "🇩🇪[🍀] 🛜Germany №2"),
        ("Italy", "🇮🇹[🍀] 🛜Italy"),
        ("Ukraine_S", "🇺🇦[🍀] 🛜Ukraine"),
        ("SPB", "🇷🇺[🍀] 🛜St.Petersburg 🕊️"),
        ("Finland_S", "🇫🇮[🍀] 🛜Finland"),
        ("USA", "🇺🇸[🍀] 🛜USA"),
    ],
    "user_ivan.txt": [
        ("SIGN", "‼️⬇️Только моб. интернет"),
        ("RLTE_EU", "🇪🇺🔵МегаФон №1"),
        ("RLTE_RU", "🇷🇺🔵МегаФон №2"),
        ("FLTE_EU", "🇪🇺🟠МегаФон №3"),
        ("FLTE_RU", "🇷🇺🟠МегаФон №4"),
        ("WLTE_EU", "🇪🇺⚪МегаФон №5"),
        ("WLTE_RU", "🇷🇺⚪МегаФон №6"),
        ("DLTE_EU", "🇪🇺🟢МегаФон №7"),
        ("DLTE_RU", "🇷🇺🟢МегаФон №8"),
        ("SIGN", "‼️⬇️VPN для Wi-Fi"),
        ("Germany", "🇩🇪🛜Germany🤖"),
        ("Austria", "🇦🇹🛜Austria🤖"),
        ("Poland", "🇵🇱🛜Poland🤖"),
        ("France", "🇫🇷🛜France🤖"),
        ("Italy", "🇮🇹🛜Italy🤖"),
        ("NL_2", "🇳🇱🛜Netherlands"),
        ("Finland_S", "🇫🇮🛜Finland"),
        ("USA", "🇺🇸🛜USA🤖"),
    ],
    "user_egor.txt": [
        ("SIGN", "‼️⬇️Только моб. интернет"),
        ("RLTE_EU", "🇪🇺🔵Т2 EU 1547692696"),
        ("RLTE_RU", "🇷🇺🔵Т2 RU 1547692696"),
        ("FLTE_EU", "🇪🇺🟠Т2 EU 1547692696"),
        ("FLTE_RU", "🇷🇺🟠Т2 RU 1547692696"),
        ("WLTE_EU", "🇪🇺⚪Т2 EU 1547692696"),
        ("WLTE_RU", "🇷🇺⚪Т2 RU 1547692696"),
        ("DLTE_EU", "🇪🇺🟢Т2 EU 1547692696"),
        ("DLTE_RU", "🇷🇺🟢Т2 RU 1547692696"),
        ("SIGN", "‼️⬇️VPN для Wi-Fi"),
        ("Germany", "🇩🇪🛜Germany"),
        ("Austria", "🇦🇹🛜Austria"),
        ("Poland", "🇵🇱🛜Poland"),
        ("France", "🇫🇷🛜France"),
        ("Italy", "🇮🇹🛜Italy"),
        ("USA", "🇺🇸🛜USA"),
    ],
    "user_m.txt": [
        ("RLTE_EU", "🇪🇺🔵МТС №1"),
        ("RLTE_RU", "🇷🇺🔵МТС №2"),
        ("FLTE_EU", "🇪🇺🟠МТС №3"),
        ("FLTE_RU", "🇷🇺🟠МТС №4"),
        ("WLTE_EU", "🇪🇺⚪МТС №5"),
        ("WLTE_RU", "🇷🇺⚪МТС №6"),
        ("DLTE_EU", "🇪🇺🟢МТС №7"),
        ("DLTE_RU", "🇷🇺🟢МТС №8"),
        ("SPB_Private_WiFi", "🇷🇺🛜Санкт-Петербург"),
        ("NL_2", "🇳🇱🛜Нидерланды"),
        ("Poland_S", "🇵🇱🛜Польша"),
        ("Germany", "🇩🇪🛜Германия"),
    ],
    "user_grisha.txt": [
        ("SIGN", "‼️⬇️Только моб. интернет"),
        ("RLTE_EU", "🇪🇺🔵МТС №1"),
        ("RLTE_RU", "🇷🇺🔵МТС №2"),
        ("FLTE_EU", "🇪🇺🟠МТС №3"),
        ("FLTE_RU", "🇷🇺🟠МТС №4"),
        ("WLTE_EU", "🇪🇺⚪МТС №5"),
        ("WLTE_RU", "🇷🇺⚪МТС №6"),
        ("DLTE_EU", "🇪🇺🟢МТС №7"),
        ("DLTE_RU", "🇷🇺🟢МТС №8"),
        ("SIGN", "‼️⬇️VPN для Wi-Fi"),
        ("Germany", "🇩🇪🛜Germany"),
        ("Austria", "🇦🇹🛜Austria"),
        ("Poland", "🇵🇱🛜Poland"),
        ("France", "🇫🇷🛜France"),
        ("Italy", "🇮🇹🛜Italy"),
        ("USA", "🇺🇸🛜USA"),
    ],
    "user_andrey10.txt": [
        ("SIGN", "‼️⬇️Только моб. интернет"),
        ("RLTE_EU", "🇪🇺🔵МТС №1"),
        ("RLTE_RU", "🇷🇺🔵МТС №2"),
        ("FLTE_EU", "🇪🇺🟠МТС №3"),
        ("FLTE_RU", "🇷🇺🟠МТС №4"),
        ("WLTE_EU", "🇪🇺⚪МТС №5"),
        ("WLTE_RU", "🇷🇺⚪МТС №6"),
        ("DLTE_EU", "🇪🇺🟢МТС №7"),
        ("DLTE_RU", "🇷🇺🟢МТС №8"),
        ("SIGN", "‼️⬇️VPN для Wi-Fi"),
        ("Germany", "🇩🇪🛜Germany"),
        ("Austria", "🇦🇹🛜Austria"),
        ("Poland", "🇵🇱🛜Poland"),
        ("France", "🇫🇷🛜France"),
        ("Italy", "🇮🇹🛜Italy"),
        ("USA", "🇺🇸🛜USA"),
    ],
    "user_radaa.txt": [
        ("SIGN", "‼️⬇️Только моб. интернет"),
        ("RLTE_EU", "🇪🇺🔵МТС EU 1756521878"),
        ("RLTE_RU", "🇷🇺🔵МТС RU 1756521878"),
        ("FLTE_EU", "🇪🇺🟠МТС EU 1756521878"),
        ("FLTE_RU", "🇷🇺🟠МТС RU 1756521878"),
        ("WLTE_EU", "🇪🇺⚪МТС EU 1756521878"),
        ("WLTE_RU", "🇷🇺⚪МТС RU 1756521878"),
        ("DLTE_EU", "🇪🇺🟢МТС EU 1756521878"),
        ("DLTE_RU", "🇷🇺🟢МТС RU 1756521878"),
        ("SIGN", "‼️⬇️VPN для Wi-Fi"),
        ("Germany", "🇩🇪🛜Germany 1756521878"),
        ("Austria", "🇦🇹🛜Austria 1756521878"),
        ("Poland", "🇵🇱🛜Poland 1756521878"),
    ],
    "user_vovo.txt": [
        ("SIGN", "‼️⬇️Только моб. интернет"),
        ("RLTE_EU", "🇪🇺🔵МТС EU 5413957454"),
        ("RLTE_RU", "🇷🇺🔵МТС RU 5413957454"),
        ("FLTE_EU", "🇪🇺🟠МТС EU 5413957454"),
        ("FLTE_RU", "🇷🇺🟠МТС RU 5413957454"),
        ("WLTE_EU", "🇪🇺⚪МТС EU 5413957454"),
        ("WLTE_RU", "🇷🇺⚪МТС RU 5413957454"),
        ("DLTE_EU", "🇪🇺🟢МТС EU 5413957454"),
        ("DLTE_RU", "🇷🇺🟢МТС RU 5413957454"),
        ("SIGN", "‼️⬇️VPN для Wi-Fi"),
        ("Germany", "🇩🇪🛜Germany 5413957454"),
        ("Austria", "🇦🇹🛜Austria 5413957454"),
        ("Poland", "🇵🇱🛜Poland 5413957454"),
    ],
    "user_nikita.txt": [
        ("RLTE_EU", "🇪🇺🔵МТС №1"),
        ("RLTE_RU", "🇷🇺🔵МТС №2"),
        ("FLTE_EU", "🇪🇺🟠МТС №3"),
        ("FLTE_RU", "🇷🇺🟠МТС №4"),
        ("WLTE_EU", "🇪🇺⚪МТС №5"),
        ("WLTE_RU", "🇷🇺⚪МТС №6"),
        ("DLTE_EU", "🇪🇺🟢МТС №7"),
        ("DLTE_RU", "🇷🇺🟢МТС №8"),
        ("SPB_Private", "🇷🇺🔴Дневник (моб.интернет)"),
        ("Germany", "🇩🇪🛜Germany №1🤖"),
        ("Poland_S", "🇵🇱🛜Poland №1"),
        ("Poland", "🇵🇱🛜Poland №2🤖"),
        ("NL_2", "🇳🇱🛜Netherlands"),
        ("Estonia_S", "🇪🇪🛜Estonia"),
        ("France", "🇫🇷🛜France🤖"),
        ("Germany_S", "🇩🇪🛜Germany №2"),
        ("Italy", "🇮🇹🛜Italy🤖"),
        ("Ukraine_S", "🇺🇦🛜Ukraine"),
        ("Finland_S", "🇫🇮🛜Finland"),
        ("USA", "🇺🇸🛜USA🤖"),
    ],
    "user_d.txt": [
        ("SPB_Private_WiFi", "🇷🇺Санкт-Петербург Wi-Fi"),
        ("SPB_Private", "🇷🇺Моб. интернет"),
    ],
    "user_nikita_clash.txt": {
        "clash": True,
        "servers": [
        ("Germany", "🇩🇪🛜Germany №1🤖"),
        ("Poland_S", "🇵🇱🛜Poland №1"),
        ("Poland", "🇵🇱🛜Poland №2🤖"),
        ("NL_2", "🇳🇱🛜Netherlands"),
        ("Estonia_S", "🇪🇪🛜Estonia"),
        ("France", "🇫🇷🛜France🤖"),
        ("Germany_S", "🇩🇪🛜Germany №2"),
        ("Italy", "🇮🇹🛜Italy🤖"),
        ("Ukraine_S", "🇺🇦🛜Ukraine"),
        ("Finland_S", "🇫🇮🛜Finland"),
        ("USA", "🇺🇸🛜USA🤖"),
        ("RLTE_EU", "🇪🇺🔵МТС №1"),
        ("RLTE_RU", "🇷🇺🔵МТС №2"),
        ("FLTE_EU", "🇪🇺🟠МТС №3"),
        ("FLTE_RU", "🇷🇺🟠МТС №4"),
        ("WLTE_EU", "🇪🇺⚪МТС №5"),
        ("WLTE_RU", "🇷🇺⚪МТС №6"),
        ("DLTE_EU", "🇪🇺🟢МТС №7"),
        ("DLTE_RU", "🇷🇺🟢МТС №8"),
        ("SPB_Private", "🇷🇺🔴Дневник (моб.интернет)"),
    ]
    },
    "kust_clash.txt": {
        "clash": True,
        "servers": [
        ("Germany", "🇩🇪[🍀] 🛜Germany №1"),
        ("Poland_S", "🇵🇱[🍀] 🛜Poland №1"),
        ("Poland", "🇵🇱[🍀] 🛜Poland №2"),
        ("NL_2", "🇳🇱[🍀] 🛜Netherlands"),
        ("Estonia_S", "🇪🇪[🍀] 🛜Estonia"),
        ("France", "🇫🇷[🍀] 🛜France"),
        ("Germany_S", "🇩🇪[🍀] 🛜Germany №2"),
        ("Italy", "🇮🇹[🍀] 🛜Italy"),
        ("Ukraine_S", "🇺🇦[🍀] 🛜Ukraine"),
        ("SPB", "🇷🇺[🍀] 🛜St.Petersburg 🕊️"),
        ("Finland_S", "🇫🇮[🍀] 🛜Finland"),
        ("USA", "🇺🇸[🍀] 🛜USA"),
        ("FLTE_EU", "🇪🇺[🍀] 🟠Моб. интернет"),
        ("FLTE_RU", "🇷🇺[🍀] 🟠Моб. интернет"),
        ("SPB_Private", "🇷🇺[🍀] 🔴Дневник (моб.интернет)"),
    ]
    },
}

























